### ISSUE TITLE
v3.0.0-beta5客户端使用tcp作为handler且配置转发链时panic

### ISSUE THREAD

**Issue by yqt** [go-gost/gost#103]
启动命令
```
./gost-linux-amd64-3.0.0-beta.5 -L tcp://:8000 -F socks5+ws://user:pass@:2080
```
请求`8000`端口后出现panic：
```
{"level":"warning","msg":"load global TLS certificate files failed, use random generated certificate","time":"2022-09-22T01:17:51.709+08:00"}
{"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:8000/tcp","service":"service-0","time":"2022-09-22T01:17:51.709+08:00"}
{"handler":"tcp","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:8000","msg":"127.0.0.1:30242 <> 127.0.0.1:8000","remote":"127.0.0.1:30242","service":"service-0","time":"2022-09-22T01:18:19.597+08:00"}
{"duration":168347,"handler":"tcp","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:8000","msg":"127.0.0.1:30242 >< 127.0.0.1:8000","remote":"127.0.0.1:30242","service":"service-0","time":"2022-09-22T01:18:19.597+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf440f5]

goroutine 12 [running]:
github.com/go-gost/core/chain.(*NodeGroup).Next(...)
	/home/gerry/code/go-gost/core/chain/node.go:122
github.com/go-gost/x/handler/forward/local.(*forwardHandler).Handle(0xc000186000, {0x1451408, 0xc000126020}, {0x145d4b0?, 0xc00011e018}, {0x0?, 0x0?, 0x0?})
	/home/gerry/code/go-gost/x/handler/forward/local/handler.go:84 +0x415
github.com/go-gost/core/service.(*service).Serve.func1()
	/home/gerry/code/go-gost/core/service/service.go:145 +0x394
created by github.com/go-gost/core/service.(*service).Serve
	/home/gerry/code/go-gost/core/service/service.go:125 +0x505

```

**Comment by ginuerzh** [comment]
try beta.6
