### ISSUE TITLE
Tun on windows(gost v3.0.0-nightly.20240426): panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zoghal** [go-gost/gost#482]
Hi Dear

On Windows by running this command line:
```
gost -L "tun://:0/SERVER_IP:8421?net=192.168.10.101"  -F relay+wss://SERVER_IP:8444
```
I get this error
```
{"handler":"tun","kind":"service","level":"info","listener":"tun","msg":"listening on :0/udp","service":"service-0","time":"2024-05-24T06:17:09.547+03:30"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xc716b7]

goroutine 6 [running]:
golang.org/x/sys/windows.UTF16PtrToString(0x232b650?)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.19.0/windows/syscall_windows.go:119 +0x17
golang.zx2c4.com/wintun.logMessage(0x0?, 0x77a1fd8c0, 0x20)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:51 +0x11b
syscall.SyscallN(0x7ffb29503fb0?, {0xc000493a20?, 0x3?, 0xc000493a38?})
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/syscall_windows.go:544 +0x107
syscall.Syscall(0x233bce0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/syscall_windows.go:482 +0x35
golang.zx2c4.com/wintun.CreateAdapter({0x181df15?, 0x0?}, {0x18251e8, 0x9}, 0x0)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:92 +0xd4
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0x181df15, 0x6}, 0x0?, 0x546)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20220703234212-c31a7b1ab478/tun/tun_windows.go:73 +0x45
golang.zx2c4.com/wireguard/tun.CreateTUN(...)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20220703234212-c31a7b1ab478/tun/tun_windows.go:65
github.com/go-gost/x/listener/tun.(*tunListener).createTunDevice(0xc0000d0200)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20240426125656-332a3a1cd09f/listener/tun/tun.go:53 +0x35
github.com/go-gost/x/listener/tun.(*tunListener).createTun(0xc0000d0200)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20240426125656-332a3a1cd09f/listener/tun/tun_windows.go:19 +0x5f
github.com/go-gost/x/listener/tun.(*tunListener).listenLoop.func1(0xc0000d0200, 0xc00029a000)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20240426125656-332a3a1cd09f/listener/tun/listener.go:70 +0x32
github.com/go-gost/x/listener/tun.(*tunListener).listenLoop(0xc0000d0200)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20240426125656-332a3a1cd09f/listener/tun/listener.go:104 +0x5e
created by github.com/go-gost/x/listener/tun.(*tunListener).Init in goroutine 1
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20240426125656-332a3a1cd09f/listener/tun/listener.go:61 +0x185
`

**Comment by ginuerzh** [comment]
Root cause: the `wintun.dll` log callback receives a garbage pointer from the driver in certain failure scenarios, and `golang.zx2c4.com/wintun` passes it directly to `windows.UTF16PtrToString()` without nil-checking — panicking the entire process. The upstream lib hasn't been updated since Jan 2023 and this hasn't been fixed.

Fix in go-gost/x@9ea1076: added `defer/recover` in the `listenLoop` inner closure of `tun`/`tungo`/`tap` listeners. Panics from `createTun`/`createTap` are now converted to logged errors (e.g. `"panic in createTun: ..."`), and the retry loop recovers after a 1-second sleep instead of crashing the process.
