### ISSUE TITLE
Multiple Processes - BUG

### ISSUE THREAD

**Issue by steom** [go-gost/gost#508]
gost -L http://:8080 -- -L http://:8000 -- -L socks://:1080 -F http://:8000

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xe2dbc8]

goroutine 12 [running]:
os.(*ProcessState).exited(...)
        /opt/hostedtoolcache/go/1.22.3/x64/src/os/exec_posix.go:83
os.(*ProcessState).Exited(...)
        /opt/hostedtoolcache/go/1.22.3/x64/src/os/exec.go:157
main.worker(0x0, {0xc0004a80e0?, 0x10e7ce5?, 0x2?}, 0x0?, 0xc00042e898)
        /home/runner/work/gost/gost/cmd/gost/main.go:67 +0x1c8
main.init.0.func1(0x0, {0xc0000829c1?, 0x0?})
        /home/runner/work/gost/gost/cmd/gost/main.go:49 +0xb1
created by main.init.0 in goroutine 1
        /home/runner/work/gost/gost/cmd/gost/main.go:46 +0x1ca

**Comment by ginuerzh** [comment]
Which version and platform do you use? The output of the command below:
```
gost -V
```

**Comment by ginuerzh** [comment]
Fix committed in `b985e51`. The multi-worker ` -- ` path had several issues that combined to cause the panic:

1. **Nil `ProcessState` dereference** — when one worker finishes and its `defer cancel()` kills siblings, `exec.CommandContext` can return with `cmd.ProcessState == nil`. Added nil guard.
2. **Data race on `ret`** — multiple goroutines wrote to a bare `int` without synchronization → replaced with `atomic.Int32`.
3. **Premature cancellation** — each goroutine had `defer cancel()`, so the first worker to exit would kill all others. Moved `cancel()` to after `wg.Wait()`.
4. **`log.Fatal` on cancellation** — context cancellation errors triggered `log.Fatal`, killing the parent process. Added `ctx.Err() == nil` guard so only genuine errors are fatal.

These should all be fixed now. Please give the latest nightly/master build a try when you can.
